on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - name: Checkout code
      # https://github.com/actions/checkout/releases/tag/v4.1.1
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Install Go
      # https://github.com/actions/setup-go/releases/tag/v5.0.0
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: 'go.mod'

    # Really just checking that it compiles
    - run: go test -race -v ./...
